<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LinkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('newspapers_links')->insert([
            // Magazines
            [
                'parent_id' => null,
                'menu_id' => Menu::MAGAZINE,
                'web_data_id' => 1,
                'title' => 'Animals',
                'class' => 'animals',
                'description' => '',
                'link' => '/magazines/animals',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 1,
                'right' => 2,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 1,
                'menu_id' => Menu::MAGAZINE,
                'web_data_id' => 2,
                'title' => 'Cats',
                'class' => 'cats',
                'description' => '',
                'link' => '/magazines/animals/cats',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 4,
                'right' => 5,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 1,
                'menu_id' => Menu::MAGAZINE,
                'web_data_id' => 3,
                'title' => 'Dogs',
                'class' => 'dogs',
                'description' => '',
                'link' => '/magazines/animals/dogs',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 2,
                'right' => 3,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 1,
                'menu_id' => Menu::MAGAZINE,
                'web_data_id' => 4,
                'title' => 'Horses',
                'class' => 'horses',
                'description' => '',
                'link' => '/magazines/animals/horses',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 6,
                'right' => 7,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 1,
                'menu_id' => Menu::MAGAZINE,
                'web_data_id' => 5,
                'title' => 'Arabian Horses',
                'class' => 'arabian-horses',
                'description' => '',
                'link' => '/magazines/animals/arabian-horses',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 8,
                'right' => 9,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // News
            [
                'parent_id' => null,
                'menu_id' => Menu::NEWS,
                'web_data_id' => 6,
                'title' => 'World News',
                'class' => 'world-news',
                'description' => '',
                'link' => '/news/world-news',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 1,
                'right' => 12,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 6,
                'menu_id' => Menu::NEWS,
                'web_data_id' => 7,
                'title' => 'Major Newspapers',
                'class' => 'major-newspapers',
                'description' => '',
                'link' => '/news/world-news/major-newspapers',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 2,
                'right' => 3,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 6,
                'menu_id' => Menu::NEWS,
                'web_data_id' => 8,
                'title' => 'News Search Engines & Archives',
                'class' => 'news-search-engines-and-archives',
                'description' => '',
                'link' => '/news/world-news/news-search-engines-and-archives',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 4,
                'right' => 5,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 6,
                'menu_id' => Menu::NEWS,
                'web_data_id' => 9,
                'title' => 'World News Services',
                'class' => 'world-news-services',
                'description' => '',
                'link' => '/news/world-news/world-news-services',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 6,
                'right' => 7,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 6,
                'menu_id' => Menu::NEWS,
                'web_data_id' => 10,
                'title' => 'Radio',
                'class' => 'radio',
                'description' => '',
                'link' => '/news/world-news/radio',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 8,
                'right' => 9,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => 6,
                'menu_id' => Menu::NEWS,
                'web_data_id' => 11,
                'title' => 'Television',
                'class' => 'television',
                'description' => '',
                'link' => '/news/world-news/television',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 10,
                'right' => 11,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Main menu
            [
                'parent_id' => null,
                'menu_id' => Menu::MAIN_MENU,
                'web_data_id' => 12,
                'title' => 'Home',
                'class' => '',
                'description' => '',
                'link' => '/',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 1,
                'right' => 2,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::MAIN_MENU,
                'web_data_id' => 13,
                'title' => 'Magazines',
                'class' => '',
                'description' => '',
                'link' => '/magazines',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 3,
                'right' => 4,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::MAIN_MENU,
                'web_data_id' => 14,
                'title' => 'News by Categories',
                'class' => '',
                'description' => '',
                'link' => '/news',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 5,
                'right' => 6,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::MAIN_MENU,
                'web_data_id' => 15,
                'title' => 'News by Countries',
                'class' => '',
                'description' => '',
                'link' => '/countries',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 7,
                'right' => 8,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::MAIN_MENU,
                'web_data_id' => 16,
                'title' => 'News by United States',
                'class' => 'news-by-united-states',
                'description' => '',
                'link' => '/countries/north-and-central-america/usa',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 9,
                'right' => 10,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::MAIN_MENU,
                'web_data_id' => 17,
                'title' => 'Blogs',
                'class' => 'blogs',
                'description' => '',
                'link' => '/blogs',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 11,
                'right' => 12,
                'visibility_roles' => '',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Header
            [
                'parent_id' => null,
                'menu_id' => Menu::HEADER,
                'web_data_id' => 18,
                'title' => 'About us',
                'class' => 'about-us',
                'description' => '',
                'link' => '/about-us',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 1,
                'right' => 2,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::HEADER,
                'web_data_id' => 19,
                'title' => 'Privacy policy',
                'class' => 'privacy',
                'description' => '',
                'link' => '/privacy-policy',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 3,
                'right' => 4,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::HEADER,
                'web_data_id' => 20,
                'title' => 'Contact',
                'class' => 'contact',
                'description' => '',
                'link' => '/contact',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 5,
                'right' => 6,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'parent_id' => null,
                'menu_id' => Menu::HEADER,
                'web_data_id' => 21,
                'title' => 'Sitemap',
                'class' => 'sitemap-index',
                'description' => '',
                'link' => '/sitemap-index',
                'body' => '',
                'target' => '',
                'rel' => '',
                'status' => 1,
                'left' => 7,
                'right' => 8,
                'visibility_roles' => '["1", "2", "3"]',
                'params' => '',
                'publish_start' => null,
                'publish_end' => null,
                'created_at' => now(),
                'updated_at' => now()
						],
						[
							'parent_id' => null,
							'menu_id' => Menu::HEADER, 
							'web_data_id' => 22, 
							'title' => 'Log in',
							'class' => 'log-in',
							'description' => '',
							'link' => '/login', 
							'body' => '',
							'target' => '',
							'rel' => '',
							'status' => 1,
							'left' => 9, 
							'right' => 10,
							'visibility_roles' => '', 
							'params' => '',
							'publish_start' => null,
							'publish_end' => null,
							'created_at' => now(),
							'updated_at' => now()
					],
					[
						'parent_id' => null,
						'menu_id' => Menu::HEADER, 
						'web_data_id' => 23, 
						'title' => 'Register',
						'class' => 'register',
						'description' => '',
						'link' => '/register', 
						'body' => '',
						'target' => '',
						'rel' => '',
						'status' => 1,
						'left' => 11, 
						'right' => 12,
						'visibility_roles' => '', 
						'params' => '',
						'publish_start' => null,
						'publish_end' => null,
						'created_at' => now(),
						'updated_at' => now()
				],
				[
					'parent_id' => null,
					'menu_id' => Menu::HEADER, 
					'web_data_id' => 24, 
					'title' => 'Logut',
					'class' => 'logout',
					'description' => '',
					'link' => '/logout', 
					'body' => '',
					'target' => '',
					'rel' => '',
					'status' => 1,
					'left' => 13, 
					'right' => 14,
					'visibility_roles' => '', 
					'params' => '',
					'publish_start' => null,
					'publish_end' => null,
					'created_at' => now(),
					'updated_at' => now()
			],
						
        ]);
    }
}
